name: Build & Test Argo CD Watcher Notifier
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  checks: write
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: delivops/workflows/.github/workflows/ecr-build.yaml@main
    secrets: inherit
    with:
      image_name: argocd-notifier
      tag: ${{github.sha}}
      push: false
