name: Publish Argo CD Watcher Notifier
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  publish:
    uses: delivops/workflows/.github/workflows/ecr-build.yaml@main
    secrets: inherit
    needs: bump-version
    with:
      image_name: argocd-watcher-notifier
      tag: ${{needs.bump-version.outputs.new_tag}},latest
