name: Tag & Publish Argo CD Watcher Notifier
on:
  push:
    branches:
      - main
  workflow_dispatch:

# permissions:
#   id-token: write
#   contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.name == 'argocd-notifier' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.bump-version.outputs.new_tag }},ghcr.io/${{ github.repository }}:latest
